### PR TITLE
Allow namespace cols

### PR DESCRIPTION
**Pull request by karissawhiting**
**What changes are proposed in this pull request?**

I adjusted how API results are processed/flattened to consistently allow for new namespace columns that users may add to customize their cBioPortal instances. 

The only example I can find of this in the wild is with the GENIE data base, which has namespace columns but they are blank. 

```r
set_cbioportal_db("genie-private.cbioportal.org/api")
f <- get_fusions_by_study("nsclc_genie_bpc")
```

@jalavery @hfuchs5 if you have time, could you please give this a try with the examples you were having issues with and see if 1) mutations/CNA returns the same data as before and 2) fusions are now working?

  **If there is an GitHub issue associated with this pull request, please provide link.**

  --------------------------------------------------------------------------------

  Reviewer Checklist (if item does not apply, mark is as complete)

- [ ] PR branch has pulled the most recent updates from master branch. Ensure the pull request branch and your local version match and both have the latest updates from the master branch.
- [ ] If a new function was added, function included in `_pkgdown.yml`
- [ ] If a bug was fixed, a unit test was added for the bug check
- [ ] Run `pkgdown::build_site(run_dont_run = TRUE)`. Check the R console for errors, and review the rendered website.
- [ ] Code coverage is suitable for any new functions/features. Review coverage with `withr::with_envvar(new = c("NOT_CRAN" = "true")`. Begin in a fresh R session without any packages loaded.
- [ ] R CMD Check runs without errors, warnings, and notes
- [ ] `usethis::use_spell_check()` runs with no spelling errors in documentation

When the branch is ready to be merged into master:
- [ ] Update `NEWS.md` with the changes from this pull request under the heading "`# cbioportalR (development version)`". If there is an issue associated with the pull request, reference it in parentheses at the end update (see `NEWS.md` for examples).
- [ ] Run `codemetar::write_codemeta()`
- [ ] Run `usethis::use_spell_check()` again
- [ ] Approve Pull Request
- [ ] Merge the PR

### CODE REVIEW

**Comment by jalavery** [comment]
@karissawhiting Thank you for making these updates!

**Mutations & CNA**
I compared the mutations and CNA data that are returned from the previous version of the package with the version of the data returned based on this PR and confirm that they match. 

**Fusions**
For my own memory because I totally forgot about the details of this since we originally emailed about it, copying your email to Ino here: *Looking further into this, it looks like the API now returns an additional field called “namespaceColumns” for the GENIE fusions. This is getting returned as a new list item appended to the results and is throwing off our previous code used to unnest the API results.* I think you discovered this after we were trying to pull the fusions data and nothing was being returned (0 rows returned but error wasn't being thrown). 

With the version of the package in this PR I can now successfully pull fusions data! 🎉 

**Comparison with data returned from genieBPC package**
Not sure if this is useful/necessary, but I was trying to compare the binary gene matrix returned based on data from cbioportalR vs based on the genomic data returned by the genieBPC package. The CNA and fusions require reformatting to feed into `create_gene_binary()`, but it looks like `pivot_cna_longer` is no longer part of cBioPortalR - is there a way I can easily reformat the CNA file? I think I have code from Hannah that reformats the fusions file. I'm also not matching on mutations alone, but want to revisit this tomorrow.

Thank you!!

**Comment by karissawhiting** [comment]
Thank you @jalavery ! 

Yes, the fusions issue is the one you mentioned. Happy to hear it's now returning the data correctly.

Good idea comparing with genieBPC, I didn't think of that. `pivot_cna_wider()` is part of the current version of {gnomeR} and should be working (https://mskcc-epi-bio.github.io/gnomeR/reference/pivot_cna_wider.html), but please let us know if you have any issues with it. We don't yet have a function to reformat fusions data available but as you mentioned Hannah has some code for that if needed.

Thanks again!

**Comment by jalavery** [comment]
Ha, would be good if I were checking for `pivot_cna_wider()` in the right package. Thank you! 

My results of `create_gene_binary()` aren't matching when I use the portal data vs the genieBPC (synapse) data. When I compare to the source data, the results of `create_gene_binary()` match the source data in both cases, but it seems like the source data differs between what is on the portal vs what is on Synapse. Lmk if you have a few mins today to touch base to figure out how to proceed - thank you!

**Comment by hfuchs5** [comment]
Can confirm that I can also pull fusions using this version of the code! Let me know when you meet and maybe I can hop on a zoom with you. I'm still investigating the differences in fusions from cbioportal vs Synapse.

**Pull request merged**
